# Generated by Django 3.2.19 on 2023-05-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230509_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='game_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='gametable',
            name='table_no',
            field=models.IntegerField(default=None),
        ),
    ]
