# Generated by Django 3.2.19 on 2023-05-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230509_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='game_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='gametable',
            name='table_no',
            field=models.IntegerField(),
        ),
    ]
