# Generated by Django 3.2.19 on 2023-05-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20230509_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='game_name',
            field=models.CharField(default='Snooker', max_length=40),
        ),
    ]
