# Generated by Django 3.2.19 on 2023-05-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_gametable_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='game_name',
            field=models.CharField(default='Snooker', max_length=40, null=True),
        ),
    ]
