# Generated by Django 3.2.19 on 2023-05-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_gametable_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametable',
            name='game_name',
        ),
    ]
