# Generated by Django 3.2.19 on 2023-05-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_gametable_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='game_name',
            field=models.CharField(default='Snooker', max_length=40),
        ),
    ]
