# Generated by Django 3.2.19 on 2023-05-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_gametable_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametable',
            name='table_no',
        ),
    ]
