# Generated by Django 3.2.19 on 2023-05-10 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0010_remove_gametable_table_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOfBirth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_date', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-user_id'],
            },
        ),
    ]
