# Generated by Django 3.2.19 on 2023-05-18 18:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
