# Generated by Django 3.2.19 on 2023-05-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_gametable_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametable',
            name='image',
        ),
    ]
