# Generated by Django 3.2.19 on 2023-05-18 18:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_gametable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
