# Generated by Django 3.2.19 on 2023-05-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_gametable_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='game_id',
            new_name='table_number',
        ),
        migrations.RemoveField(
            model_name='gametable',
            name='game_id',
        ),
        migrations.AddField(
            model_name='gametable',
            name='table_number',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gametable',
            name='price',
            field=models.FloatField(),
        ),
    ]
