# Generated by Django 3.2.19 on 2023-05-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20230518_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gametable',
            options={'ordering': ['-table_number']},
        ),
    ]
